version: '2'
services:
  board-server:
    image: lissonpsantos2/ubuntu-phps
    restart: always
    volumes:
      - ./:/home/server/
    ports:
      - 8090:80
    stdin_open: true
    tty: true
    entrypoint:
      - bash
      - "entrypoint.sh"
    working_dir: /home/server/
    mem_limit: 2g

  mongo:
    image: 'mongo'
    volumes:
      - './.docker/mongo/data:/data/db:z'
    ports:
      - '27003:27017'
