services:
    app:
        build:
            context: ./.docker/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: trelassio/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - trelassio
        depends_on:
            - mailpit
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
          - '${FORWARD_MAILPIT_PORT:-1025}:1025'
          - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
          - trelassio
    mongo:
      image: mongo:4.2
      volumes:
        - './.docker/mongo/data:/data/db:z'
      ports:
        - '27003:27017'
      networks:
        - trelassio
networks:
  trelassio:
    driver: bridge
