#!/bin/bash

#Install vendor/sail
docker run --rm \
    -u "$(id -u):$(id -g)" \
    -v "$(pwd):/var/www/html" \
    -w /var/www/html \
    laravelsail/php82-composer:latest \
    composer install --ignore-platform-reqs

# Start containers
./vendor/bin/sail up -d

#Compile front
./vendor/bin/sail npm install
./vendor/bin/sail npm run dev

#Create .envs
if [ ! -f .env  ];
then
    cp .env.example .env.testing
fi

if [ ! -f .env.testing  ];
then
    cp .env.testing.example .env.testing
fi

#Create key
./vendor/bin/sail artisan key:g
